# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/svn/01_mcu/vivado/mcu.cache/wt [current_project]
set_property parent.project_path C:/svn/01_mcu/vivado/mcu.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/svn/01_mcu/vivado/mcu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  C:/svn/01_mcu/vhdl/mcu_pkg.vhd
  C:/svn/01_mcu/vhdl/cpu_ctrl.vhd
  C:/svn/01_mcu/vhdl/cpu_prc.vhd
  C:/svn/01_mcu/vhdl/cpu_reg.vhd
  C:/svn/01_mcu/vhdl/cpu_alu.vhd
  C:/svn/01_mcu/vhdl/ram.vhd
  C:/svn/01_mcu/vhdl/cpu.vhd
  C:/svn/01_mcu/vhdl/bus.vhd
  C:/svn/01_mcu/vhdl/gpio.vhd
  C:/svn/01_mcu/vhdl/rom.vhd
  C:/svn/01_mcu/vhdl/mcu.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mcu -part xc7z010clg400-1 -resource_sharing off


write_checkpoint -force -noxdef mcu.dcp

catch { report_utilization -file mcu_utilization_synth.rpt -pb mcu_utilization_synth.pb }
