# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/zynq_top.bd
# Block Designs: The module: 'zynq_top' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_processing_system7_0_0 || ORIG_REF_NAME==zynq_top_processing_system7_0_0}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_ps7_0_axi_periph_0/zynq_top_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_top_ps7_0_axi_periph_0}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_rst_ps7_0_100M_0/zynq_top_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_top_rst_ps7_0_100M_0}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_axi_slave_if_0_1/zynq_top_axi_slave_if_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_axi_slave_if_0_1 || ORIG_REF_NAME==zynq_top_axi_slave_if_0_1}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_auto_pc_0/zynq_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_auto_pc_0 || ORIG_REF_NAME==zynq_top_auto_pc_0}]

# Block Designs: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/zynq_top.bd
# Block Designs: The module: 'zynq_top' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_processing_system7_0_0/zynq_top_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_processing_system7_0_0 || ORIG_REF_NAME==zynq_top_processing_system7_0_0}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_ps7_0_axi_periph_0/zynq_top_ps7_0_axi_periph_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_top_ps7_0_axi_periph_0}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_rst_ps7_0_100M_0/zynq_top_rst_ps7_0_100M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_top_rst_ps7_0_100M_0}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_axi_slave_if_0_1/zynq_top_axi_slave_if_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_axi_slave_if_0_1 || ORIG_REF_NAME==zynq_top_axi_slave_if_0_1}]

# IP: C:/git/add/lab_2/lab_2.srcs/sources_1/bd/zynq_top/ip/zynq_top_auto_pc_0/zynq_top_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_top_auto_pc_0 || ORIG_REF_NAME==zynq_top_auto_pc_0}]
